name: Go
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.14', '1.15' ]

    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Go Test
        run: go test -v ./...
